version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CHROMA_PORT=8001
      - OPENAI_API_KEY=sk-proj-XXX
    depends_on:
      - chroma
    
  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma

volumes:
  chroma-data: